spring:
  application:
    name: demo-elk
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: es:9200

logging:
  level:
    root: info
    com.soboot: debug

logstash:
  # logstash部署的服务器IP
  host: lsh
server:
  port: 9900